name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Django App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Black formatter check
      run: |
        black --check .

    - name: Run Flake8 linter
      run: |
        flake8 .

    - name: Run tests with coverage
      run: |
        coverage run --source='.' manage.py test
        coverage report
        coverage xml

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: coverage.xml

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Create deployment package
      run: |
        sudo apt-get update -y
        sudo apt-get install -y zip
        rm -f swe-app.zip
        zip -r swe-app.zip \
          manage.py \
          Procfile \
          requirements.txt \
          runtime.txt \
          .ebextensions \
          mysite \
          polls \
          static \
          --exclude "**/__pycache__/*" \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "*.pytest_cache/*" \
          --exclude "*.coverage*" \
          --exclude "coverage.xml"

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: swe-app1
        environment_name: Swe-app1-env
        version_label: ${{ github.run_number }}
        region: us-east-2
        deployment_package: swe-app.zip
        wait_for_deployment: true
